In [1]:
from statsbombpy import sb
import json
import pandas as pd

In [32]:
with open('/Users/rachelyang/Desktop/StatsBomb/open-data-master/data/events/7298.json') as f:
  data = json.load(f)

# print(data) # checking the data
# print(len(data)) # checking the length of the data

# converting json file into a pandas dataframe
df = pd.DataFrame([data[0]])
for x in range(1, len(data)):
    temp_df = pd.DataFrame([data[x]])
    # print(temp_df)
    df = pd.concat([df, temp_df])
    #df = pd.concat(temp_df,ignore_index = True)
df

# df = pd.DataFrame([data[0]])
# df2 = pd.DataFrame([data[1]])
# df = df.append(df2, ignore_index = True)
# df

#df = pd.read_json('/Users/rachelyang/Desktop/StatsBomb/open-data-master/data/events/7430.json', orient ='index')
# print(data.values())

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,...,counterpress,duel,ball_recovery,interception,block,substitution,foul_committed,foul_won,injury_stoppage,bad_behaviour
0,0b483cd2-1d36-49a0-85c2-149a9de553df,1,1,00:00:00.000,0,0,"{'id': 35, 'name': 'Starting XI'}",1,"{'id': 746, 'name': 'Manchester City WFC'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,2c873afb-73bb-48a1-9fd5-bfe1400b4a83,2,1,00:00:00.000,0,0,"{'id': 35, 'name': 'Starting XI'}",1,"{'id': 746, 'name': 'Manchester City WFC'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,040940a1-5972-431e-b6ac-e723edd8e7c2,3,1,00:00:00.000,0,0,"{'id': 18, 'name': 'Half Start'}",1,"{'id': 746, 'name': 'Manchester City WFC'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,5ba286bd-c397-4ac4-b12f-6bace943afce,4,1,00:00:00.000,0,0,"{'id': 18, 'name': 'Half Start'}",1,"{'id': 746, 'name': 'Manchester City WFC'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,2a456ec2-352c-499b-b5cc-e68bf84c7e9a,5,1,00:00:00.100,0,0,"{'id': 30, 'name': 'Pass'}",2,"{'id': 971, 'name': 'Chelsea FCW'}","{'id': 9, 'name': 'From Kick Off'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,49e5bbe8-de8b-4b45-a168-4e130960c371,3789,2,00:48:50.958,93,50,"{'id': 30, 'name': 'Pass'}",228,"{'id': 746, 'name': 'Manchester City WFC'}","{'id': 7, 'name': 'From Goal Kick'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,733c3090-32b6-4c6f-870e-80d288ba927f,3790,2,00:48:53.558,93,53,"{'id': 30, 'name': 'Pass'}",228,"{'id': 746, 'name': 'Manchester City WFC'}","{'id': 7, 'name': 'From Goal Kick'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,f5388757-108e-4280-95c1-e95aa4a8a281,3791,2,00:48:57.038,93,57,"{'id': 9, 'name': 'Clearance'}",228,"{'id': 746, 'name': 'Manchester City WFC'}","{'id': 7, 'name': 'From Goal Kick'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,72cdfa47-772b-4487-bdea-12dcb36461a2,3792,2,00:49:04.531,94,4,"{'id': 34, 'name': 'Half End'}",228,"{'id': 746, 'name': 'Manchester City WFC'}","{'id': 7, 'name': 'From Goal Kick'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,1939c3fe-9e07-4698-8c09-f43715b7982b,3793,2,00:49:04.531,94,4,"{'id': 34, 'name': 'Half End'}",228,"{'id': 746, 'name': 'Manchester City WFC'}","{'id': 7, 'name': 'From Goal Kick'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN